name: Publish Package to npm
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Building package
        run: npm run build
      - name: Publishing package
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}